### ISSUE TITLE
npe when trying to resolve url for a second streamcloud download 

### ISSUE THREAD

**Issue by lumue** [lumue/getdown#5]
this occurs if one tries to execute more than on streamcloud download. no matter if parallel or consecutive.

log:
```
2015-06-20 19:41:13.257 DEBUG 22425 --- [nio-8001-exec-7] i.g.l.g.a.s.w.DownloadJsonRpcController  : download job for http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html added and started
2015-06-20 19:41:13.257 DEBUG 22425 --- [pool-2-thread-2] i.g.l.g.c.d.job.AsyncDownloadJobRunner   : starting download for url http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html
2015-06-20 19:41:13.258 DEBUG 22425 --- [pool-2-thread-2] i.g.l.g.c.download.job.HttpDownloadJob   : start download for url http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html
2015-06-20 19:41:13.264 DEBUG 22425 --- [pool-2-thread-2] i.g.l.g.c.download.job.HttpDownloadJob   : creating ContentLocation for http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html
2015-06-20 19:41:13.264 DEBUG 22425 --- [pool-2-thread-2] .g.c.d.r.ContentLocationResolverRegistry : looking up ContentLocationResolver for streamcloud.eu
2015-06-20 19:41:13.264 DEBUG 22425 --- [pool-2-thread-2] .g.c.d.r.ContentLocationResolverRegistry : returning ContentLocationResolver io.github.lumue.getdown.hosts.streamcloud.StreamcloudContentLocationResolver for streamcloud.eu
2015-06-20 19:41:13.264 DEBUG 22425 --- [pool-2-thread-2] g.h.s.StreamcloudContentLocationResolver : load page at http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html to retrieve session cookie
2015-06-20 19:41:13.264 DEBUG 22425 --- [pool-2-thread-2] g.h.s.StreamcloudContentLocationResolver : 
Sending 'GET' request to URL : http://streamcloud.eu/w7l5g5enduu9/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-DIMENSION.mkv.html
2015-06-20 19:41:18.593 ERROR 22425 --- [pool-2-thread-2] i.g.l.g.c.download.job.HttpDownloadJob   : Error running Job io.github.lumue.getdown.core.download.job.HttpDownloadJob@9573f29c :

java.lang.NullPointerException: no session cookie found in response headers
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.github.lumue.getdown.hosts.streamcloud.StreamcloudContentLocationResolver.createStreamcloudSessionId(StreamcloudContentLocationResolver.java:105)
	at io.github.lumue.getdown.hosts.streamcloud.StreamcloudContentLocationResolver.resolve(StreamcloudContentLocationResolver.java:78)
	at io.github.lumue.getdown.core.download.job.HttpDownloadJob.createContentLocation(HttpDownloadJob.java:89)
	at io.github.lumue.getdown.core.download.job.HttpDownloadJob.run(HttpDownloadJob.java:42)
	at io.github.lumue.getdown.core.download.job.AsyncDownloadJobRunner$1.run(AsyncDownloadJobRunner.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lumue** [comment]
fixed, use builtin apache httpclient session management
